### ISSUE TITLE
NullPointerException when running both the scripts

### ISSUE THREAD

**Issue by Piruzzolo** [astrelsky/Ghidra-Cpp-Class-Analyzer#1]
It shows up when running either the python scripts.
Here the reported trace
```
Uncaught Exception! 
java.lang.NullPointerException
	at org.python.core.Py.dispatchToChecker(Py.java:2490)
	at org.python.core.Py.isInstance(Py.java:2347)
	at org.python.core.__builtin__.isinstance(__builtin__.java:712)
	at org.python.core.Py.exceptionToString(Py.java:1372)
	at org.python.core.Py.exceptionToBytes(Py.java:1339)
	at org.python.core.Py.displayException(Py.java:1316)
	at org.python.core.PyException.printStackTrace(PyException.java:89)
	at docking.DockingErrorDisplay.buildStackTrace(DockingErrorDisplay.java:146)
	at docking.DockingErrorDisplay.createErrorDialog(DockingErrorDisplay.java:114)
	at docking.DockingErrorDisplay.doShowDialog(DockingErrorDisplay.java:98)
	at docking.DockingErrorDisplay.lambda$showDialog$0(DockingErrorDisplay.java:91)
	at docking.DockingErrorDisplay$$Lambda$614.00000000B9C754A0.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:673)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2019-Sep-23 1119 EDT
Ghidra Version: 9.1-BETA
Java Home: C:\Program Files\AdoptOpenJDK\jdk-12.0.1.12-openj9
JVM Version: AdoptOpenJDK 12.0.1
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-6TBLE83
```

I'm on latest released version, 1.2

**Comment by astrelsky** [comment]
Unfortunately the trace doesn't tell me much. I just pushed a commit of some changes to the scripts I had done but hadn't pushed yet. I'm not sure if it is actually from the script or a result of something else.

What compiler was the binary compiled with? It would also be helpful to know how the binary was linked, either static or dynamic. I have noted some issues when analyzing classes which subclass something in a dynamic library. I have a fix for that but it's patchy and not ready yet.

If the latest commit doesn't fix this, check the log by going to help->show log in the ghidra project window.

**Comment by Piruzzolo** [comment]
The binary should be statically linked, compiled with Visual Studio (old version, 6 I guess). Thanks, hope to try soon

**Comment by astrelsky** [comment]
This may be related to [#1079](https://github.com/NationalSecurityAgency/ghidra/issues/1079)

**Comment by astrelsky** [comment]
This should have been resolved by recent commits in this repo and in ghidra. If this is still an issue feel free to reopen it.

**Comment by james-tate** [comment]
I am getting quite a bit of these also on various programs. I am using 9.1-DEV. I have not had a chance yet to take a look at where it's specifically failing. I should be able to get you an example in a day or so.

**Comment by astrelsky** [comment]
> I am getting quite a bit of these also on various programs. I am using 9.1-DEV. I have not had a chance yet to take a look at where it's specifically failing. I should be able to get you an example in a day or so.

Ok I'll look into it. In the meantime may you provide some information as to which architecture and compiler of the programs your running the scripts with?

**Comment by james-tate** [comment]
gcc/x86

**Comment by astrelsky** [comment]
@james-tate The latest commit should have resolved the NPE. Any ClassTypeInfo which inherits from a class in an external library needs the external library imported into the project in order for it to be resolved. For now any analysis will stop at that point. I'll work on a solution for when the user doesn't have the external library sometime this week or next week.
