### ISSUE TITLE
java.lang.Exception: Vtable for std::type_info not found

### ISSUE THREAD

**Issue by Noh3choo** [astrelsky/Ghidra-Cpp-Class-Analyzer#39]
I have two aarch64 binaries with partial symbols I am working with and when I run the `GCC RTTI Analyzer` on either executable I get the following exception:

```
(These messages are also written to the application log file)

Vtable for std::type_info not found
java.lang.Exception: Vtable for std::type_info not found
	at cppclassanalyzer.scanner.ItaniumAbiRttiScanner.getStaticReferences(ItaniumAbiRttiScanner.java:314)
	at cppclassanalyzer.scanner.ItaniumAbiRttiScanner.getReferences(ItaniumAbiRttiScanner.java:287)
	at cppclassanalyzer.scanner.ItaniumAbiRttiScanner.applyTypeInfoTypes(ItaniumAbiRttiScanner.java:208)
	at cppclassanalyzer.scanner.ItaniumAbiRttiScanner.doScan(ItaniumAbiRttiScanner.java:140)
	at cppclassanalyzer.scanner.ItaniumAbiRttiScanner.scan(ItaniumAbiRttiScanner.java:132)
	at ghidra.app.plugin.prototype.GccRttiAnalyzer.added(GccRttiAnalyzer.java:119)
	at ghidra.app.plugin.core.analysis.OneShotAnalysisCommand.applyTo(OneShotAnalysisCommand.java:47)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:688)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:788)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:832)


```
commit: `718168727082d96fe0dd6c5b997170205bdc6721`
Ghidra Version: 9.2.3
OS: Ubuntu 20.04 LTS

**Comment by astrelsky** [comment]
Hmm. It appears that the type info for `std::type_info` is found but it either can't find the vtable or verification is failing.

Is the symbol for `std::type_info::vtable` present? If so I would like to see what the data there looks like.

**Comment by Noh3choo** [comment]
`readelf` shows `std::type_info` 
```
  4747: 0000000000416dcc     4 FUNC    GLOBAL DEFAULT    3 std::type_info::~type_info()
  4752: 000000000073a8c0    16 OBJECT  GLOBAL DEFAULT   11 typeinfo for std::type_info
  4791: 0000000000416dcc     4 FUNC    GLOBAL DEFAULT    3 std::type_info::~type_info()
```

However I do not see a `vtable` in the symbols like I do for other classes.

**Comment by astrelsky** [comment]
> `readelf` shows `std::type_info`
> 
> ```
>   4747: 0000000000416dcc     4 FUNC    GLOBAL DEFAULT    3 std::type_info::~type_info()
>   4752: 000000000073a8c0    16 OBJECT  GLOBAL DEFAULT   11 typeinfo for std::type_info
>   4791: 0000000000416dcc     4 FUNC    GLOBAL DEFAULT    3 std::type_info::~type_info()
> ```
> 
> However I do not see a `vtable` in the symbols like I do for other classes.

Is this something you can share?

**Comment by martmists-gh** [comment]
An android native binary I'm working on has this exact same issue.
[here](https://github.com/SDM660-Project/vendor_dirac/blob/master/vendor/lib/libDiracAPI_SHARED.so) is a link to the file in question

**Comment by astrelsky** [comment]
> An android native binary I'm working on has this exact same issue.
> [here](https://github.com/SDM660-Project/vendor_dirac/blob/master/vendor/lib/libDiracAPI_SHARED.so) is a link to the file in question

I will take a look when I have some free time. However, please be advised that you will encounter some other problems when using the analyzer on Android binaries. Android vtables in particular don't seem to follow the common "rules" such as having the destructors in function table slots 0 and 1 but the analyzer might still assume it is. There is some verification for the destructors but depending on how complex it is expected to be it may incorrectly determine it to be a destructor.
