### ISSUE TITLE
Incompatible with Ghidra 10.3

### ISSUE THREAD

**Issue by Martmists-GH** [astrelsky/Ghidra-Cpp-Class-Analyzer#70]
Clicking anywhere in the decompiler window gives an error, making it impossible to use ghidra while the plugin is installed (as ghidra does not allow me to disable it in the UI)

<details>
<summary>Error</summary>
<pre><code>'ghidra.program.model.data.GenericCallingConvention ghidra.program.model.listing.FunctionSignature.getGenericCallingConvention()'
java.lang.NoSuchMethodError: 'ghidra.program.model.data.GenericCallingConvention ghidra.program.model.listing.FunctionSignature.getGenericCallingConvention()'
	at cppclassanalyzer.data.manager.ClassTypeInfoManagerDB.getType(ClassTypeInfoManagerDB.java:363)
	at cppclassanalyzer.decompiler.action.FillOutClassAction.isEnabledForDecompilerContext(FillOutClassAction.java:38)
	at ghidra.app.plugin.core.decompile.actions.AbstractDecompilerAction.lambda$isEnabledForContext$0(AbstractDecompilerAction.java:66)
	at ghidra.app.plugin.core.decompile.DecompilerActionContext.checkActionEnablement(DecompilerActionContext.java:208)
	at ghidra.app.plugin.core.decompile.actions.AbstractDecompilerAction.isEnabledForContext(AbstractDecompilerAction.java:65)
	at docking.ComponentPlaceholder.contextChanged(ComponentPlaceholder.java:538)
	at docking.DockingWindowManager.contextChanged(DockingWindowManager.java:2292)
	at docking.AbstractDockingTool.contextChanged(AbstractDockingTool.java:212)
	at ghidra.framework.plugintool.PluginTool.contextChanged(PluginTool.java:1503)
	at ghidra.app.plugin.core.decompile.DecompilerProvider.contextChanged(DecompilerProvider.java:697)
	at ghidra.app.plugin.core.decompile.DecompilerProvider.locationChanged(DecompilerProvider.java:538)
	at ghidra.app.decompiler.component.DecompilerController.locationChanged(DecompilerController.java:265)
	at ghidra.app.decompiler.component.DecompilerPanel.fieldLocationChanged(DecompilerPanel.java:902)
	at docking.widgets.fieldpanel.FieldPanel$CursorHandler.notifyCursorChanged(FieldPanel.java:2161)
	at docking.widgets.fieldpanel.FieldPanel$CursorHandler.setCursorPos(FieldPanel.java:1956)
	at docking.widgets.fieldpanel.FieldPanel$FieldPanelMouseAdapter.mousePressed(FieldPanel.java:1350)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2023-May-12 1514 CEST
Ghidra Version: 10.3
Java Home: /usr/lib/jvm/java-17-openjdk
JVM Version: N/A 17.0.7
OS: Linux 6.3.3-arch1-1 amd64</code></pre></summary>

**Comment by astrelsky** [comment]
That is why I haven't put out a release for 10.3 - yet. I can get a build of where that doesn't occur but I haven't been able to get the tests to pass yet.

**Comment by Martmists-GH** [comment]
Is there a way to disable the plugin in ghidra? It's blocking pretty much everything, and the checkbox doesn't allow me to disable it as far as I can tell.

**Comment by astrelsky** [comment]
> Is there a way to disable the plugin in ghidra? It's blocking pretty much everything, and the checkbox doesn't allow me to disable it as far as I can tell.

Delete it. If you hadn't edited the version in in the `extension.properties` it wouldn't have activated.

**Comment by Martmists-GH** [comment]
The zip file seems to be owned by ad admin rather than me, so unfortunately that's not possible. Also, the version in the menu still shows 10.2.3, so I don't think anyone edited it.

**Comment by astrelsky** [comment]
> The zip file seems to be owned by ad admin rather than me, so unfortunately that's not possible. Also, the version in the menu still shows 10.2.3, so I don't think anyone edited it.

You still need to delete the file. Either way that is something you would need to figure out since you wouldn't be able to update the plugin if I had a release for 10.3 anyway.

**Comment by astrelsky** [comment]
Note that this is not a bug in this plugin. If the plugin version is for an older version of Ghidra, then Ghidra should not be loading it.
